name: hajj_and_umrah
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1 #version flutter

dependencies: #def
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.7
  camera: ^0.10.5+9
  image: ^4.0.15
  google_mlkit_pose_detection: ^0.14.0
  # tflite_flutter: ^0.10.4
  # tflite_flutter_helper: ^0.5.2
  path_provider: ^2.0.15
  path: ^1.8.3
  http: ^1.1.0
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  geolocator: ^13.0.4
  # firebase_core: ^3.9.0
  # firebase_auth: ^5.3.4
  # cloud_firestore: ^5.0.0
  arcore_flutter_plugin: ^0.1.0  # For Android AR
  arkit_plugin: ^1.1.1 # For iOS AR
  google_maps_flutter: ^2.10.0  # For Google Maps integration
  permission_handler: ^12.0.0  # To request camera permissions
  email_auth: ^2.0.0 # for security
  google_fonts: ^6.2.1
  url_launcher: ^6.2.4
  easy_pdf_viewer: ^1.0.8 #allow put pdf 
  heart_bpm: ^2.0.0+0
  # arcore_flutter_plugin: ^0.1.0
  # vector_math: ^2.1.0 
  font_awesome_flutter: ^10.4.0

dev_dependencies: #lib
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

 



flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/images/
    # - lib/assets/icons/
    - lib/assets/pdf/
